---
abstract: 'Provide a series of C extensions for DBD::SQLite and some helper functions to load them'
author:
  - 'Ryan Voots E<lt>simcop2387@simcop2387.infoE<gt>'
build_requires: {}
configure_requires:
  Alien::Base::ModuleBuild: '0.005'
  Archive::Zip: '0'
  DBD::SQLite: '0'
  File::ShareDir: '0'
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBD-SQLite-BundledExtensions
provides:
  DBD::SQLite::BundledExtensions:
    file: lib/DBD/SQLite/BundledExtensions.pm
    version: '0.002'
requires:
  Alien::Base: '0.005'
  DBD::SQLite: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.002'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
